server:
  port: 8069
  ssl:
    enabled: false
    # Allow the Spring context to close all active requests before shutting down the server
    # Please ref: https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
  shutdown: graceful

logging:
 level:
    root: info
    org.springframework.web: info
